### ISSUE TITLE
Blank page when trying to add booking

### ISSUE THREAD

**Issue by hugbat** [compucorp/civibooking#144]
Hi

I'm setting-up CiviCRM with CiviBooking for a community project and have an issue when trying to add a booking.  I've added resource configuration sets, resources types and resources, however when I try to add a booking the screen is blank where I would expect the resources to be displayed in a calendar view.

![image](https://cloud.githubusercontent.com/assets/24450924/21003176/cc03f79a-bd8e-11e6-8429-340b4ea439cd.png)

I am running CiviCRM 4.7.13, Drupal 7.52, CiviBooking 1.5, Ubuntu 16.04 LTS.  I get the same result on Firefox, Chrome and Edge.

This issues appears to be very similar to https://github.com/compucorp/civibooking/issues/121.

Firefox Browser Console shows many JS errors of the following type:
"The resource from “http://MYSITE//sites/default/custom_ext/uk.co.compucorp.civicrm.booking/templates/CRM/Booking/Form/SelectResource.js?r=iH0za” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff)."

And a single instance of the error "TypeError: scheduler.createTimelineView is not a function", with a lot of other noise.

I have set-up my CiviCRM extensions directory alongside the 'files' directory as suggested on the instructions page for enabling CiviCRM extensions, https://wiki.civicrm.org/confluence/display/CRMDOC/Extensions.

Following the commentary in issue https://github.com/compucorp/civibooking/issues/121 I've checked the following and they appear to be correct:
Resource URLS on http://MYSITE/civicrm/admin/setting/url?reset=1
Upload Directories on http://MYSITE/civicrm/admin/setting/path?reset=1

Therefore the solution proposed solution under https://github.com/compucorp/civibooking/issues/121 has not resolved the issue in this instance.

I think I may have made a mistake somewhere in my installation and set-up.  

Can anyone offer some insight into this issue?

Thanks for your help.

Regards

Hugh

**Comment by jamienovick** [comment]
Hi Hugh, what browser are you using? Can you try chrome or firefox?

**Comment by guanhuan** [comment]
Hi @hugbat ,

Thanks for providing all the details and seems you have spent a good amount of time to solve the problem yourself.

We haven't got any similar issue reported us. From the information you provided, I believe the issue is probably either caused by your local installation or your browser settings. 

I noticed that the url to the js file your provided has two slashes after your base_url "MYSITE" - "http://MYSITE//sites/default/custom_ext/uk.co.compucorp.civicrm.booking/templates/CRM/Booking/Form/SelectResource.js?r=iH0za". If this is not a typo then it might be the key to solve your problem (check if you added an extra slash in CiviCRM directory/URL settings). Otherwise, you might find issues like this informative https://blogs.msdn.microsoft.com/ieinternals/2010/09/27/google-image-search-and-ie9-beta/.

Let us know your progress.

Best

**Comment by hugbat** [comment]
Hi @guanhuan 

Thanks for your swift response.  That was not a typo in the URL.  

I had specified absolute paths for the Extensions, Custom PHP and Custom Template Directories, and the Extension Resource URL.  I had left the other settings using the path variables [civicrm.root] and [civicrm.files].

So, I have reset the Extensions, Custom PHP and Custom Template Directories using the [cms.root] variable - for example "[cms.root]/sites/default/custom.ext".

This has resolved the issue, which I'll now close!

Thanks again for your help.

Regards

Hugh
