### ISSUE TITLE
CiviBooking - CiviCRM v4.5 support status

### ISSUE THREAD

**Issue by routinet** [compucorp/civibooking#93]
Our organization is looking into CiviBooking to assist with reservations.  It looks like a nice project, but a bit shy of "ready for prime-time".  I noticed the last commit was more than 3 weeks ago, and appears to be a minor bug fix.  Prior to that, the last commit was back in June. 

Is development continuing on this extension?  What is the current state - alpha?  beta?  usable?   Is there somewhere I can see a progress report on the project?

**Comment by Upperholme** [comment]
As far as I'm aware version 4.4.x has been designated as a 'Long Term Support" (LTS) version so all the security fixes identified in 4.5.x are being backported. So, for a good while yet 4.4.x and Civibooking should be fine.

**Comment by sgladstone** [comment]
Jamie - Can you provide a rough date estimate for when this extension will work under CiviCRM version 4.5.x?

**Comment by sgladstone** [comment]
Unless dates for a plan to support CiviCRM 4.5 ( and hopefully 4.6 which will likely be stable in another 6 weeks) are publicly shared,  I am planning to to tell any of my clients and prospects that this booking extension has been abandoned.

**Comment by jamienovick** [comment]
Hi Sarah,

Can I ask how many of your clients are currently using CiviBooking?

As I've said above, for support for CiviCRM 4.5 we would need a client to fund this development. It wouldn't be too significant amount and we would estimate 20 hours of work required.

Also, given that 4.6 is just around the corner, and as you know, that 4.5 is unlikely to be a LTS release we are currently holding off 4.5 support so that we can potentially do the upgrade compatibility work together at the same time, or may just support 4.6 directly depending on client needs.

We do have a client who has proposed to fund the necessary development and has some big plans for the module (including online booking), but the project has been delayed by a few months as they have had some staff losses.

As I said before, if you have an immediate need and are able to fund the development then of course please do let us know and we would be really pleased to bring the development forward, but in the meantime if you do feel that your clients shouldn't be using CiviBooking then of course that is up to your best judgement.

I would add that the 4.4 version is of course available to those who need,

Best

Jamie

**Comment by sgladstone** [comment]
Currently no clients are using it because of the issues with version 4.5.

**Comment by petednz** [comment]
I added a StackExchange post so just linking back here from that http://civicrm.stackexchange.com/questions/4606/what-is-the-status-of-civibooking-for-civicrm-4-6-x

**Comment by samuelsov** [comment]
Is it possible to start a Make It Happen on this so people can contribute to the update / improvements of this module. Maybe no organisation is ready to pay for the full 20h but a few could pay enough to reach the goal ?

**Comment by guanhuan** [comment]
Hi All,

We have just released V1.5alpha. It is a pre-release with 4.5 and 4.6 compatibility.
https://github.com/compucorp/civibooking/releases/tag/v1.5alpha

Feel free to try it out and report any issue back to us. Thanks in advance.
